In [2]:
import torch

In [3]:
t: torch.Tensor = torch.tensor([
    [0.0275, 0.2928, -0.0673, 0.0091, -0.2381, -0.1013, 0.0629, 0.3827, -0.0429],
    [-0.1159, 0.1298, -0.0803, 0.0268, -0.1646, -0.0231, -0.1705, 0.2590, 0.1646],
    [-0.0583, 0.2696, 0.1578, -0.1233, -0.0556, -0.4193, -0.0929, 0.2257, 0.1437],
    [-0.0147, 0.2270, 0.0529, -0.1243, -0.0623, -0.1973, -0.1104, 0.1529, 0.0326]
])
t

tensor([[ 0.0275,  0.2928, -0.0673,  0.0091, -0.2381, -0.1013,  0.0629,  0.3827,
         -0.0429],
        [-0.1159,  0.1298, -0.0803,  0.0268, -0.1646, -0.0231, -0.1705,  0.2590,
          0.1646],
        [-0.0583,  0.2696,  0.1578, -0.1233, -0.0556, -0.4193, -0.0929,  0.2257,
          0.1437],
        [-0.0147,  0.2270,  0.0529, -0.1243, -0.0623, -0.1973, -0.1104,  0.1529,
          0.0326]])

In [4]:
t[0]

tensor([ 0.0275,  0.2928, -0.0673,  0.0091, -0.2381, -0.1013,  0.0629,  0.3827,
        -0.0429])

In [13]:
t[:, :-2]

tensor([[ 0.0275,  0.2928, -0.0673,  0.0091, -0.2381, -0.1013,  0.0629],
        [-0.1159,  0.1298, -0.0803,  0.0268, -0.1646, -0.0231, -0.1705],
        [-0.0583,  0.2696,  0.1578, -0.1233, -0.0556, -0.4193, -0.0929],
        [-0.0147,  0.2270,  0.0529, -0.1243, -0.0623, -0.1973, -0.1104]])